# Generated by Django 3.2.8 on 2021-10-13 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0002_remove_team_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('username', models.EmailField(max_length=55, unique=True)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField()),
                ('login_time', models.DateTimeField()),
                ('time_spent', models.BigIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('user_type', models.IntegerField(choices=[(1, 'admin'), (2, 'coach'), (3, 'player')], default=3)),
                ('score', models.FloatField(default=0)),
                ('height', models.FloatField(default=0)),
                ('login_count', models.PositiveIntegerField(default=0)),
                ('team', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='team.team')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
