# Generated by Django 3.2.8 on 2021-10-16 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customauth', '0002_alter_myuser_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='login_time',
            field=models.DateTimeField(null=True),
        ),
    ]
