# Generated by Django 3.2.8 on 2021-10-16 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customauth', '0003_alter_myuser_login_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='score',
        ),
    ]
