# Generated by Django 3.2.8 on 2021-10-13 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20211010_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='round',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='team_one_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='team_two_score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
