# Generated by Django 3.2.8 on 2021-10-16 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20211013_2251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameactivity',
            name='activity',
        ),
        migrations.AddField(
            model_name='gameactivity',
            name='is_goal',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='gameactivity',
            name='is_try',
            field=models.BooleanField(default=0),
        ),
    ]
