# Generated by Django 3.2.8 on 2021-10-16 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20211016_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameactivity',
            name='is_goal',
        ),
        migrations.RemoveField(
            model_name='gameactivity',
            name='is_try',
        ),
        migrations.AddField(
            model_name='gameactivity',
            name='activity',
            field=models.IntegerField(default=0),
        ),
    ]
